CREATE OR REPLACE TYPE CITIZEN_IDENTIFY_CARD AS
  OBJECT(
    NUMBER_ NUMBER(12),
    NAME VARCHAR2(50),
    DATE_OF_BIRTH DATE,
    SEX VARCHAR2(50),
    NATIONALITY VARCHAR2(50),
    PLACE_OF_ORIGIN VARCHAR2(50),
    PLACE_OF_RESIDENCE VARCHAR2(50),
    DATE_OF_EXPIRY DATE
  );
  CREATE TABLE CITIZEN_IDENTIFY_CARD_TABLE OF CITIZEN_IDENTIFY_CARD (
    PRIMARY KEY (NUMBER_)
  );
  CREATE OR REPLACE TYPE ACCOUNT AS OBJECT(
    ACCOUNT_NUMBER NUMBER(12),
    BANK VARCHAR2(50),
    ALIAS VARCHAR2(50),
    BALANCE NUMBER
  );
   CREATE OR REPLACE TYPE CLIENT AS OBJECT(
    NUMBER_ NUMBER(12),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50)
  );
  CREATE TABLE CLIENT_TABLE OF CLIENT (
    PRIMARY KEY(NUMBER_)
  );